herbert_core/classes/instrument_classes/@oriented_lattice/bmatrix.m
Change `angder` -> `angdeg` as required. This was causing test failures.
=> Fix typo in `oriented_lattice\bmatrix.m`

herbert_core/classes/instrument_classes/@oriented_lattice/bmatrix.m
The second return value in `bmatrix` was not being set correctly due to a typo.
=> Fix @oriented_lattice/bmatrix typo `arly`->`arlu`

CMakeLists.txt, _LowLevelCode/CPP/cpp_communicator/CMakeLists.txt, _LowLevelCode/CPP/get_ascii_file/CMakeLists.txt, _LowLevelCode/Fortran/source_mex/CMakeLists.txt, cmake/herbert_AddMex.cmake
This PR writes a `herbert_add_mex` function in CMake. This function basically does the same thing as CMake's built-in `matlab_add_mex` except it will copy the mex library to a given location after compilation. The default copy location is `herbert_core/DLL`
=> Add post build commands for mex libs

herbert_core/graphics/@IX_dataset_1d/private/custom_errorbars.m
The errorbar cap length was introduced as an optional named value 'CapSize', with units in points, in MATLAB 2016b.
Setting the cap length to zero has the effect that very-short errorbars (compared to the vertical axis) are not drawn, compared to the old method of drawing the symbols and errorbars separately which draws a dot in the same situation.
This function can be simplified if the minimum version of MATLAB supported by Herbert is ever increased to 2016b. (Efficient use of Euphonic and/or brille by Horace requires support for Python `memoryview` objects, which was introduced in MATLAB 2018b.)
=> Introduce 'CapSize' to custom_errorbars

herbert_core/configuration/@herbert_config/private/process_unit_test_path.m
Fix typo that was throwing an error instead of a warning - `test_path` → `tests_path`. 
Running `init_herbert.m` using the new package was throwing an error since the package does not contain the `_test` directory. This was caused by a typo. 
Add qualifier so that the warning will only be shown if a user is attempting to initialize the tests and the directory does not exist. Previously the warning/error was shown every time the package was started
=> Fix config error when unit tests are not available

tools/build_config/build.sh
This was introduced when the `cmake_flags` argument was created. The build script would raise an`unbound` error when building without this flag.
=> Fix error when calling build.sh with only --build

tools/build_config/Jenkinsfile, tools/build_config/build.sh
Increase the allowed size of the CTest results xml for tests that pass (tests that fail are automatically not truncated).
=> Increase allowed CTest ouput size

CMakeLists.txt
The reason for this comes mostly from Jenkins+Horace. Horace pulls the
Herbert build package when it runs its tests, however the testing
framework is in Herbert! Hence the test framework needs to be present in
Herbert - at least for the time being.
Ideally we would not package the _test directory at all and Horace's
tests should all be written using the new Matlab test framework. This is
probably not possible, however we should find a way to minimise the size
of the Herbert package we ship to users, but still allowing Horace to
perform its full set of tests etc.
=> Pacakge _test directory with Herbert

herbert_core/herbert_init.m, herbert_core/herbert_off.m
The function `application_off` was calling `herbert_off` which removed all paths beneath Herebert's root - except for those in the MATLABPATH environment variable. `application_off` then removed the paths AGAIN, this time also removing the paths in MATLABPATH - which we do not want.
=> Stop application_off removing paths twice

_test/CMakeLists.txt, herbert_core/admin/@opt_config_manager/OptimalConfigInfo.xml
The `herbert_init` call was previously registered as a pre-command in the `matlab_add_unit_test` function. For some reason, if herbert_init failed then the test would terminate, but no error would be raised.
Moving the `herbert_init` call inside the `try-catch` block within the test script run by CTest fixes this.
Fixes #63
=> Move herbert_init call inside CTest test script

_test/CMakeLists.txt, _test/test_utilities/test_obj2struct.m, admin/CMakeLists.txt, tools/build_config/Jenkinsfile, tools/build_config/build.ps1
This PR adds PowerShell commands to the Jenkinsfile to build, test and package the Windows version of Herbert.
Alongside this PR, the `PR-Windows-10-2019b`, `Branch-Windows-10-2019b` and the nightly `Windows-10-2019b` Jenkins pipelines have been created.
A test was failing locally and on Jenkins so https://github.com/pace-neutrons/Herbert/pull/69/commits/aba253308d0f36e21845dfd5d18dd3de6c2a2742 disables it. This should be fixed and re-enabled - the test doesn't appear to fail on Linux.
Fixes #68
=> Windows additions to jenkinsfile

cmake/herbert_FindMatlab.cmake, tools/build_config/Jenkinsfile
This solves the issue of the Windows nightly packages not being named correctly.
Fixes #72
=> Windows nightly packages name correction

tools/build_config/build.sh
Ran the build.sh script through ShellCheck (https://github.com/koalaman/shellcheck).
These changes were suggested by the script rules.
Added default in the case block to catch invalid arguments and prevent script hanging in the while loop.
=> Shellcheck updates

tools/build_config/build.ps1, tools/build_config/build.sh
This prevents potentially long processes running if the user has made a typo in some script argument. This also mirrors the behaviour in the bash build script.
=> Exit PowerShell build script early on invalid input

_test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m, _test/test_utilities/test_obj2struct.m
The test was failing on Windows Matlab R2019b due to comparing two floats without a tolerance. The difference between the numbers was of the order of 10<sup>-14</sup>. Now we compare with a tolerance.
Fixes #70
=> Fix failing utilities test on windows

tools/build_config/Jenkinsfile, tools/build_config/build.ps1
Previously we were using the "failure" stage to post `Build failed` statuses to GitHub, however this block is not entered if the build is manually aborted. This meant that aborted jobs were stuck with the "build running" status on GitHub. The `unsuccessful` post-build step is run if the build has any status other than `success`.
=> Post build failed if jenkins build aborted

_test/common_functions/MPI_Test_Common.m, _test/test_mpi_wrappers/test_CPP_MPI_exchange.m, _test/test_mpi_wrappers/test_FileBaseMPI_Framework.m
This PR makes `MPI_Tests_Common` (which most MPI tests inherit from) call `set_local_parallel_config()` on construction. It will restore the previous config on `tearDown`. 
`set_local_parallel_config` moves the config directory to `tempdir()/config`, CMake sets the environment variable `TMP` to point to within the build directory, so each Jenkins job should now have a unique place it stores its config. We do a similar thing for the message exchange folders. This should prevent the two jobs reading/writing files in the same location.
Fixes: #113
Fixes: https://github.com/pace-neutrons/Horace/issues/168
=> Fix error in Windows Jenkins jobs run concurrently

_test/test_instrument_classes/test_IX_sample.m, herbert_core/classes/instrument_classes/instrument/@IX_sample/IX_sample.m
Simple addition of the Hall Symbol to the IX_sample object. 
This makes no assertions about the structure or format of the symbol other than it is a string. 
@g5t: Additional validation could be added if it would be useful, appropriate and could be well defined. Comparing the user value against a list of "valid" values would require us to copy the some of the data included in Brille across to Herbert.
Fixes #163
=> Add Hall Symbol IX_sample

cmake/shared/PACE_AddCppUnitTest.cmake
This provides an easy regex to only run C++ tests, as well as being consistent with the Matlab tests, which are all prefixed with `Matlab.`
Fixes #127 
Fixes https://github.com/pace-neutrons/Horace/issues/165
=> Prefix C++ tests with cpp. in  CTest

_test/test_instrument_classes/test_IX_inst.m, herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst/IX_inst.m
Add Heterogeneous mixin to IX_inst base class. This allows the creation of arrays of `IX_inst` subclass containing a mix of child classes (e.g. `IX_inst_DGdisk` and `IX_inst_DGfermi`
Part of https://github.com/pace-neutrons/Horace/issues/136
=> Add support for arrays of `IX_inst`

_test/common_functions/seed_rng.m
This function seeds Matlab's RNG so that we can get reproducibility in tests that may require randomness.
This function currently lies in `Horace/_test/test_tobyfit` but should be made accessible elsewhere. I tried putting it in `Horace/_test/common_functions` but for some reason it was not on the path when the Horace tests were run. In any case, this is a better place for this function.
=> Add seed_rng to _test/common_functions

_LowLevelCode/cpp/cpp_communicator/CMakeLists.txt
The Linux version of `cpp_communicator.mex` requires dynamically linked MPICH libraries. This means we need a way to point to the required `.so` libs. I've done this by setting a relative RPATH value on the mex library. 
I toyed with using the `LD_LIBRARY_PATH` environment variable, which worked, but only if the environment variable was set before Matlab was launched. Using `setenv('LD_LIBRARY_PATH`, ...)` from within Matlab did not work. Using RPATH means users do not need to worry about setting any environment variables.
Fixes #170 
Fixes https://github.com/pace-neutrons/Horace/issues/260
=> Set relative RPATH on cpp_communicator on Linux

herbert_core/admin/tmp_dir.m, herbert_core/utilities/misc/make_config_folder.m, herbert_core/utilities/misc/try_to_create_folder.m
The issue user experienced was that if tmp folder on idaaas does not exist, Horace initialization was failing. I think, the solution is straightforward -- create such folder.
=> bug in tmpdir on idaaas

tools/build_config/build.ps1, tools/build_config/build.sh
This PR adds help to Herbert's `build.ps1` and `build.sh` build scripts. The help messages should be printed given the `-h` or `-help` flags in PowerShell and  the -h` or `--help` flags in bash. Help should also be printed if no arguments are passed to the help scripts.
Refs: https://github.com/pace-neutrons/Horace/issues/257
Fixes #179
=> Add help to build scripts

herbert_core/admin/@opt_config_manager/OptimalConfigInfo.xml, herbert_core/admin/@opt_config_manager/private/find_comp_type_.m
It was not identifying iDaaaS machines correctly. Should be fixed now.
=> bug in optimal configuration

tools/build_config/Jenkinsfile
This PR moves the declaration of pipeline parameters into the Jenkinsfile. This means we shouldn't need to do as much configuration within the Jenkins GUI.
When parameters are set in the Jenkinsfile, the pipeline's configuration will update according to the parameters specified. If running from a clean pipeline (with no configuration set in the GUI) the first build will most likely fail because the parameters were not previously set. This should not be a problem for us since the parameters I've added in the Jenkinsfile are already set in the GUI, therefore builds should be unaffected.
The new Jenkinsfile deduces what the default parameter values should be using the pipeline's name. If the pipeline's name starts with `PR-` then the Jenkinsfile will set the parameter defaults that are …
=> Move Jenkins pipeline param declaration into Jenkinsfile

tools/build_config/Jenkinsfile
The function was previously only ever returning an empty string. There's
some weirdness when setting/returning variables from within a
withCredentials block.
This fix should get the pipelines back up and running properly
=> Fix get_agent function in Jenkinsfile

tools/build_config/Jenkinsfile
This PR makes additions to the Jenkinsfile such that the Git revision being built and tested is written to a file. The file is then archived to make it accessible by other pipelines.
Fixes #231
=> Jenkins release pipelines to archive text file with Git revision SHA

_test/test_mpi/job_dispatcher_common_tests.m, herbert_core/classes/instrument_classes/instrument/@IX_mod_shape_mono/private/moments_.m, herbert_core/utilities/misc/try_to_create_folder.m
Matlab's RNG state was being overwritten in `try_to_create_folder` which was throwing off some of our tests that use random number generation. We should also not be overwriting the RNG state of users.
I've added an `onCleanup` to reset the RNG's state.
Fixes #238
Fixes https://github.com/pace-neutrons/Horace/issues/385
=> Return RNG to previous state on create_folder cleanup

herbert_core/utilities/maths/noisify.m
This PR does the following:
- it does fix #234 to correct 
- (i) interpretation of the input e and output eout as standard deviations rather than variances - sqrts and ^2s are removed
- (ii) isempty test on the error output processing at the end is switched to not isempty to allow correct comparison of input and output error sizes
- it also supports a fourth argument to pass a previously calculated max signal value to replace the locally calculated one. This allows a max to be calculated in a previous pass when paging is used.
- the existing interface is unchanged
- if the fourth argument is present, the third argument can be defaulted using a value <0.
=> fix noisify bugs #234, extend interface for paging

_test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/private/instantiate_ref_data_.m, _test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/private/preprocess.m, _test/shared/matlab_xunit_ISISextras/manage_legacy_sqw_class_rename.m
Add preprocess shim to manage conversion of sqw to sqw_old in test snapshot files; temporary code that will be removed.
=> Manage sqw class rename in test data snapshot files

tools/build_config/build.ps1
Missing quotes around strings was causing errors when paths contained spaces.
Fixes #254
=> Fix missing quotes in build.ps1 commands

herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_par.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_phx.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_phx_as_par.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_phx_or_par_private.m
Round-off all detector parameters read from ASCII files to 5 significant digits -- I think its pretty simple change
=> round-off detector parameters

_test/test_data_loaders/test_asciipar_loader.m, _test/test_data_loaders/test_loader_ascii.m, herbert_core/classes/data_loaders/@a_loader/a_loader.m, herbert_core/classes/data_loaders/@asciipar_loader/asciipar_loader.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_par.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_phx.m, herbert_core/classes/data_loaders/@asciipar_loader/private/load_ASCII_phx_as_par.m, herbert_core/classes/data_loaders/@loader_ascii/load_data.m, herbert_core/classes/data_loaders/@loader_ascii/loader_ascii.m, herbert_core/classes/data_loaders/@loader_nxspe/loader_nxspe.m, herbert_core/classes/data_loaders/@rundata/get_rundata.m, herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m, herbert_core/classes/data_loaders/@rundata/private/select_loader_.m, herbert_core/classes/data_loaders/@rundata/rundata.m, herbert_core/classes/data_loaders/loaders_factory.m
Better and more consistent implementation of the asciipar truncation with the purpose of producing consistent results on any OS with any code
=> truncate asciipar

tools/build_config/Jenkinsfile
If you use Groovy string interpolation when passing credentials to a
shell command, the secret will be executed in plain text on the agent.
The Jenkins logs will still mask the credentials, but any command
logging on the agent machine will leak the secret.
Using the environment variable set by the withCredentials block means
the command does not contain the secret, any command logs will only show
an environment variable was accessed.
See https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#interpolation-of-sensitive-environment-variables.
=> Do not use Groovy interpolation for Jenkins credentials

_test/test_data_loaders/test_rundata.m, herbert_core/classes/data_loaders/@rundata/private/convert_to_struct_.m, herbert_core/classes/data_loaders/@rundata/private/find_run_id_.m, herbert_core/classes/data_loaders/@rundata/run_id.m, herbert_core/classes/data_loaders/@rundata/rundata.m, herbert_core/classes/instrument_classes/@oriented_lattice/calc_proj_matrix.m, herbert_core/utilities/scientific/calc_proj_matrix.m, herbert_core/utilities/scientific/ubmatrix.m
This small PR is the part of changes, related to urange clarification. Here I have added run_id to rundata class as apparently this number may be necessary in some gen_sqw scenarios.
=> Add run_id method to rundata class

_test/shared/matlab_xunit/xunit/TestCase.m, _test/shared/matlab_xunit/xunit/TestComponent.m, _test/shared/matlab_xunit/xunit/TestRunDisplay.m, _test/shared/matlab_xunit/xunit/TestRunLogger.m, _test/shared/matlab_xunit/xunit/TestRunMonitor.m, _test/shared/matlab_xunit/xunit/TestSuite.m, _test/shared/matlab_xunit/xunit/VerboseTestRunDisplay.m, _test/shared/matlab_xunit/xunit/skipTest.m, _test/test_utilities/test_skip.m
Add skipped tests via the skipTest function into the test suite
E.g.
```MATLAB
skipTest('I don''t like this test')
```
This will print an `S` rather than `F`, count as passed and will display detailed reasoning on `runtests -verbose` but not on standard runs.
=> 276 add skip

_test/test_data_loaders/test_rundata_rm_masked.m, herbert_core/classes/data_loaders/@rundata/rm_masked.m, herbert_core/classes/data_loaders/@rundata/rundata.m, herbert_core/classes/instrument_classes/@oriented_lattice/bmatrix.m, herbert_core/classes/instrument_classes/@oriented_lattice/ubmatrix.m, herbert_core/utilities/scientific/bmatrix.m, herbert_core/utilities/scientific/calc_proj_matrix.m
This small change is related to Horace ticket [#464](https://github.com/pace-neutrons/Horace/issues/464) and enables masking according to keys, e.g. disabling pixels with signal equal to nan or inf
=> Masking disabled on keys

_test/shared/matlab_xunit/xunit/TestSuite.m, admin/validate_herbert.m, herbert_core/utilities/files/sync_folders.m
#284 is happening because `isdir` searches the MATLAB path as well as the current working directory.
=> Address issue with isdir (searches path) vs isfolder

herbert_core/classes/MPIFramework/@ClusterParpoolWrapper/ClusterParpoolWrapper.m
Set Matlab Parpools' `JobStorageLocation` to `parallel_config.working_directory` in MPI framework.
This should stop the same directory being used by multiple different Matlab instances at the same time on Jenkins. 
`parallel_config.working_directory` evaluates to `JENKINS_WORKSPACE/build/test` on Jenkins, hence each executor should have its own (separate) copy of the folder. See [relevant Jenkins build](https://anvil.softeng-support.ac.uk/jenkins/job/PACE-neutrons/job/Herbert/job/Branch-Windows-10-2019b/28/console) where I print the value of `JobStorageLocation`.
Addresses https://github.com/pace-neutrons/Horace/issues/557
=> Set JobStorageLocation on parpool MPI clusters

admin/lint_json.m, cmake/shared/PACE_CodeAnalysis.cmake
Add ability to exclude files from mlint parsing. Syntax
`mlint_json({'files', 'to', 'scan', '**/*.m'}, 'output', 'exclude', {'excluded', 'files', '**/doc_*'});`
=> 567 lint ignore herbert

admin/lint_json.m
Fix printing useless `flist` every Jenkins run
=> Remove extraneous print

tools/build_config/Jenkinsfile
Fix for #322. Should fix the `null parameter` error on the Herbert nightly builds.
=> Herbert master builds failing on null parameter error in Jenkinsfile

tools/build_config/Jenkinsfile
Fix the CMake flag in the Jenkinsfile. This flag is important when setting package names. Whilst it was incorrect, nightly packages did not have the date appended to the name.
Addresses #330
=> Horace build flag passed to Herbert in Jenkins

herbert_core/admin/getComputerName.m
In case `getComputerName` can't find a name, return unknownPC
=> Add fallback to getComputerName

_test/test_geometry/test_box_edges.m
minor technical issue not worth mentioning in sprint reviews
=> assertElementsAlmostEqual used to check accuracy

herbert_core/utilities/misc/hlp_serial_sise.m
=> bug in hlp_serial_sise if saveobj has not been overloaded

herbert_core/utilities/classes/@IX_data_1d/IX_data_1d.m, herbert_core/utilities/classes/@IX_data_1d/private/calc_cont_frac_.m
For IX_data_1d, the function calc_continuous_fraction as implemented in the private function calc_cont_frac_, scans a single plot for points which cannot be plotted because although their value is plottable, the values either side are NaN and so lines cannot be drawn from the plottable point.
In the tests in test_tobyfit, calls to this function with one such plot work fine. However there are IX_data_1d objects with three plots in them, and they fail because the first line of calc_cont_frac_ fails - ~valid has too many arguments (it says). This PR fixes the behaviour.
As modified here the parent call calc_continuous_fraction now loops over the component plots, returns the corresponding fraction, and reports to the caller the minimum fraction of the set. This minimizes the changes required …
=> loop if more than one plot

_test/test_serializers/serializableTester1.m, _test/test_serializers/test_serializable_class.m, _test/test_serializers/test_serialize.m, _test/test_utilities/test_parse_args_namelist.m, herbert_core/utilities/classes/@serializable/private/from_bare_struct_.m, herbert_core/utilities/classes/@serializable/private/from_struct_.m, herbert_core/utilities/classes/@serializable/private/loadobj_.m, herbert_core/utilities/classes/@serializable/private/to_bare_struct_.m, herbert_core/utilities/classes/@serializable/private/to_struct_.m, herbert_core/utilities/classes/@serializable/serializable.m
small changes fix #415 
Roughly speaking, `serializable` method `to_struct` adds both `version` and `serial_name` fields. 
In addition to that, as earlier agreed, I have renamed `from_class_struc` method to `from_bare_struc` method
The reviewer should also look at https://github.com/pace-neutrons/Horace/issues/777, as I will probably make PR and merge it it immediately after merging this. The changes there are trivial -- just renames `from_class_struct` to `from_bare_struc`  whenever it used
=> serializable bug

herbert_core/classes/MPIFramework/@JobExecutor/JobExecutor.m, herbert_core/classes/MPIFramework/parallel_worker.m
Complete set of convenience functions.
Add a `setup` phase to job executor called once before entering calculation loop (non-abstract to avoid having to modify all existing JobExecutors with null function)
=> Brief improvements to parallel framework

herbert_core/classes/MPIFramework/@ClusterMPI/ClusterMPI.m, herbert_core/classes/MPIFramework/@ClusterParpoolWrapper/ClusterParpoolWrapper.m, herbert_core/classes/MPIFramework/@ClusterWrapper/ClusterWrapper.m, herbert_core/classes/MPIFramework/@parallel_config/parallel_config.m, herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_cluster_.m, herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_worker_.m
Changes the checks in `@parallel_config` and `@MPI*` classes to allow compiled workers.
When the `worker` field of `parallel_config` is set to something which is _not_ a Matlab function, then it is checked to see if it may be a compiled worker. This check considers something a compiled worker if:
* It is a full path to a existing file; OR
* It is a command on the system `PATH` (as determined by the `which` (Linux) or `where` (Windows) command).
The full path to the file is set as the worker and the `is_compiled` flag is set to true. No check is made as to whether this file is actually executable or can run Horace etc... if it is not then any parallel computation will fail further down the chain; such checks would involve (perhaps significant) modification of `worker_v2` and/or setting up …
=> Compiled workers - Herbert changes
