pace-neutrons/Herbert

admin/copy_git_hooks.m
herbert_core/configuration/@herbert_config/herbert_config.m
herbert_core/configuration/@herbert_config/private/process_unit_test_path.m

The task appeared to be much simple as `which` command in Matlab apparently returns realpath. 
This is small changes I had to do doing release. 
Similar changes are in Horace and this request is pared with the Horace one.

22 simulink to herbert

---

CMakeLists.txt
_LowLevelCode/CPP/CMakeLists.txt
_LowLevelCode/CPP/cpp_communicator/CMakeLists.txt
_LowLevelCode/CPP/get_ascii_file/CMakeLists.txt
_LowLevelCode/CPP/test/CMakeLists.txt
_LowLevelCode/CPP/test/get_ascii_file.tests/CMakeLists.txt
_LowLevelCode/CPP/test/get_ascii_file.tests/IIget_ascii_file.test.cpp
_LowLevelCode/CPP/utility/environment.cpp
_LowLevelCode/CPP/utility/environment.h
cmake/herbert_AddUnitTest.cmake
cmake/herbert_FindGTest.cmake
cmake/templates/GTest-CMakeLists.txt.in

A C++ testing framework has been written. 
One test has been written for `IIget_ascii_file.cpp` as an example and proof of concept. Tests can be run using ctest.
This is a similar setup as is implemented in Horace

Set up cpp test framework

---

admin/worker_4tests.m.template
admin/worker_v2.m.template

… DO_LOGGING variable is not available for worker_v2. Fixed
Trivial bug identified after close look at code of worker_v2

worker_v2 bug

---

tools/build_config/Jenkinsfile

The master pipeline of SL7 is set up on Jenkins. The changes in this PR are required for a successful build on the `Scientific-Linux-7-2018b` pipeline.
Currently, the pipeline is set up to build against this branch, this will be changed to `master` when this has been merged

Setup jenkins master pipeline

---

CMakeLists.txt
cmake/herbert_FindMatlab.cmake
cmake/herbert_Version.cmake

Add Matlab release string
Remove Linux flavour

Update build version to match revised format

---

_test/test_mpi/worker_4tests_local.m

Re #1 for some reason, worker_4tests_local has not been updated as it should be (equal to worker_v2) . Fixed

Bug with worker_4tests_local

---

tools/build_config/build.ps1
tools/build_config/build.sh

The script has a similar API to `build.sh` and performs the same actions but for Windows.

Write Powershell build script `build.ps1`

---

admin/herbert_on.m.template

This matches the convention used in horace_on.m.
Add indentation to smaller functions within the function script

Reaname her_default_path to default_herbert_path

---

tools/build_config/build.sh

Remove unused argument that doesn't exist in the ps1 script

Remove unused install-dir argument

---

tools/build_config/Jenkinsfile

Sets the job names in Jenkins PR and Branch builds.

Set job names in Jenkinsfile

---

_test/disabled_tests.md

List of disabled tests in Herbert

Add list of disabled tests within _test folder

---

tools/build_config/build.ps1

Minor update to build script removing unrequired directory change

Remove unrequired directory push

---

_test/test_instrument_classes/test_IX_sample.m
herbert_core/classes/MPIFramework/messages/MESS_NAMES.m
herbert_core/classes/instrument_classes/instrument/@IX_sample/IX_sample.m

This is very simple changes, defining operator == on IX_sample

Re #115 Created == operator on IX_sample

---

_test/test_admin/test_pc_spec_config.m
herbert_core/admin/@opt_config_manager/OptimalConfigInfo.xml
herbert_core/admin/@opt_config_manager/opt_config_manager.m
herbert_core/admin/@opt_config_manager/private/find_comp_type_.m
herbert_core/admin/@opt_config_manager/private/load_configuration_.m
herbert_core/admin/@opt_config_manager/private/set_into_to_config_classes_.m
herbert_core/admin/@opt_config_manager/private/set_pc_specific_config_.m

Create different default Jenkins configurations for Unix and Windows

---

_test/shared/matlab_xunit/xunit/TestCase.m
_test/shared/matlab_xunit/xunit/TestComponent.m
_test/shared/matlab_xunit/xunit/TestSuite.m
_test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m
_test/test_mpi/test_job_dispatcher_herbert.m
_test/test_mpi/test_job_dispatcher_mpiexec.m
_test/test_mpi/test_job_dispatcher_parpool.m
herbert_core/admin/is_jenkins.m

modified tests to generate additional printout on request

---

_test/disabled_tests.md
_test/shared/matlab_xunit/xunit/TestCase.m
_test/shared/matlab_xunit/xunit/TestSuite.m
_test/shared/matlab_xunit/xunit/runtests.m

This should resolve the bug and let runtests report failure if no tests were run

Bug in runtests

---

_test/test_data_loaders/test_loader_utilites.m
_test/test_data_loaders/test_rundataOldMatlab.m
_test/test_utilities/test_nexus_root.m
herbert_core/classes/data_loaders/@a_detpar_loader_interface/a_detpar_loader_interface.m
herbert_core/classes/data_loaders/@loader_nxspe/loader_nxspe.m
herbert_core/classes/data_loaders/@nxspepar_loader/nxspepar_loader.m
herbert_core/utilities/hdf_nexus/find_dataset_info.m
herbert_core/utilities/hdf_nexus/find_root_nexus_dir.m
herbert_core/utilities/hdf_nexus/write_string_sign.m

Minor change to make find_root_nexus report correct errors in case of incorrectly written user files

Update find root nexus

---

tools/build_config/Jenkinsfile
tools/build_config/build.sh

Re-implementation of https://github.com/pace-neutrons/Horace/pull/98 for Herbert

Add checkstyle to C++ build

---

_test/test_admin/test_herbert_on.m
herbert_core/classes/data_loaders/@a_detpar_loader_interface/private/parse_loadpar_arguments_.m
herbert_core/herbert_off.m

Can not imagine how to write unit test for it but the change is simple enough to be clear.
I think its the simplest solution possible.

Not remove herbert_on from path. 

---

_test/CMakeLists.txt
_test/shared/matlab_xunit/xunit/runtests.m

This is simple fix, and if tests are passing, its doing what is requested.

Runtests for single test should work

---

_test/test_mpi_wrappers/mex_Thrower.m
_test/test_mpi_wrappers/test_MException_her.m
herbert_core/admin/parallel_worker.m
herbert_core/classes/MPIFramework/messages/@MException_her/MException_her.m
herbert_core/classes/data_loaders/@a_detpar_loader_interface/private/parse_loadpar_arguments_.m

Found way to transfer advanced information about exception using rethrow command

Exception serialization, build using rethrow command

---

_LowLevelCode/cpp/cpp_communicator/CMakeLists.txt

Similar to https://github.com/pace-neutrons/Herbert/pull/171 but merging into master instead of the release branch
Fixes #170 
Fixes pace-neutrons/Horace#260

Use packaged dynamic mpich libraries (master)

---

herbert_core/classes/MPIFramework/@MessagesFilebased/MessagesFilebased.m
herbert_core/classes/data_loaders/@rundata/private/convert_to_struct_.m
herbert_core/configuration/@config_store/private/store_internal.m

These small changes fix Horace issue [#287](https://github.com/pace-neutrons/Horace/issues/287)

rundata serialization

---

_test/common_functions/JETester.m
_test/test_mpi/job_dispatcher_common_tests.m
_test/test_mpi_wrappers/test_exchange_FileBasedMPI.m
_test/test_mpi_wrappers/test_job_executor.m
herbert_core/classes/MPIFramework/@JobDispatcher/private/display_fail_jobs_.m
herbert_core/classes/MPIFramework/@MessagesFilebased/MessagesFilebased.m
herbert_core/classes/MPIFramework/@MessagesFilebased/private/parse_folder_contents_.m
herbert_core/classes/MPIFramework/@iMessagesFramework/iMessagesFramework.m
herbert_core/classes/MPIFramework/parallel_worker.m

This is to modify job migration to split only digit at the end of the job.

Better jobID migration

---

_test/test_utilities/test_resolve_path_userpath.m
herbert_core/admin/@opt_config_manager/private/find_comp_type_.m
herbert_core/admin/is_idaaas.m
herbert_core/utilities/global_path/resolve_path.m
herbert_core/utilities/xml_io_tools/xml_read.m

iDaaaS bugs

---

_test/test_utilities/test_resolve_path_userpath.m
herbert_core/utilities/global_path/check_file_writable.m

Re #207 as per review Horace [#302](https://github.com/pace-neutrons/Horace/issues/302)
separate the code, checking the file presence/write access into separate function

separate the code, checking the file presence

---

tools/build_config/Jenkinsfile

Merging changes made in https://github.com/pace-neutrons/Herbert/pull/233 to Jenkinsfile, into `rel_3_4`

Rel branch - Jenkins release pipelines to archive text file with git revision sha

---

tools/build_config/build.ps1

Herbert equivalent of https://github.com/pace-neutrons/Horace/pull/395
Fixes #225

Do not default to Visual Studio 2017 in build.ps1

---

_test/test_config/parallel_config_tester.m
_test/test_config/test_config_classes.m
admin/typical_config_settings_helper.m
herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_worker_.m
herbert_core/configuration/@config_base/config_base.m

This is the test for the issue, identified if worker is missing and some users try to set up outdated configuration

bug if worker missing

---

_test/shared/matlab_xunit_ISISextras/manage_legacy_sqw_class_rename.m

Add support for legacy dnd objects

Manage dnd class rename in test data snapshot files 

---

_test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m
herbert_core/classes/instrument_classes/@oriented_lattice/calc_proj_matrix.m

fix TestCaseWithSave for parent class

---

herbert_core/classes/data_loaders/@spe/private/read_spe_.m

more bugs identified in loaders affecting tests in Horace

truncate asciipar again

---

_test/test_data_loaders/test_rundata.m
_test/test_utilities/test_make_const_bin_boundaries.m
herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m
herbert_core/classes/data_loaders/@rundata/private/select_loader_.m
herbert_core/utilities/misc/make_const_bin_boundaries.m
herbert_core/utilities/misc/make_const_bin_boundaries_descr.m

changes from Re #269  This is simple addition of the code, responsible for axis binning. Related to uranges and generic projections

Const bin boundaries and unit test for it

---

_test/test_utilities/test_serialize.m
_test/test_utilities/test_serialize_size.m
herbert_core/utilities/misc/hlp_serial_size.m
herbert_core/utilities/misc/hlp_serialize.m

Address some of the issues in #266

Add tests and fix minor bugs

---

_LowLevelCode/cpp/cpp_communicator/serialiser/c_deserialise.cpp
_LowLevelCode/cpp/cpp_communicator/serialiser/c_serial_size.cpp
_LowLevelCode/cpp/cpp_communicator/serialiser/c_serialise.cpp
_LowLevelCode/cpp/cpp_communicator/serialiser/cpp_serialise.hpp

Fix casting warnings in serialiser

Attempt to fix cast errors

---

_LowLevelCode/cpp/cpp_communicator/serialiser/c_serialise.cpp

Fix bug in serialiser

---

herbert_core/utilities/maths/randraw.m
herbert_core/utilities/xml_io_tools/xml_tutorial_script.m

Fix encoding errors reported by MLint

Convert windows-1252 to utf8 encoding

---

admin/CMakeLists.txt

Add lint_json to cpack

---

tools/build_config/Jenkinsfile

Add the ability to skip CI based on the `do-not-build` and `do-not-test` PR labels

Add skip CI based on labels

---

CMakeLists.txt
tools/build_config/Jenkinsfile

- Set defaults via `get_param` function
- Move printing of `PR_LABELS` for general use and consistency

Set defaults in Jenkinsfile to allow easy addition of new params

---

tools/build_config/build.ps1

Update pwsh configure stage to bring Windows build in line with Linux builds

Bring Windows build in line with Linux builds

---

_test/test_utilities/test_range_add_border.m
herbert_core/classes/MPIFramework/@JobDispatcher/JobDispatcher.m
herbert_core/utilities/general/range_add_border.m
herbert_core/utilities/scientific/bmatrix.m

This is small function, moved from Horace, modified to remove duplicated code and unit tested to ensure its correctness.
May be of interest to the people, who reviewed Horace  [#591](https://github.com/pace-neutrons/Horace/issues/591) and complained about this function

range_add_border function and unit tests for it

---

_test/shared/matlab_xunit/xunit/assertExceptionThrown.m
_test/test_config/test_config_classes.m
_test/test_instrument_classes/test_IX_sample.m
_test/test_mpi_wrappers/exchange_common_tests.m
_test/test_mpi_wrappers/test_exchange_CppMPI.m

Fix `assertExceptionThrown` printing since https://github.com/pace-neutrons/Herbert/pull/334

Fix erroneous print

---

tools/build_config/Jenkinsfile

Update the Jenkinsfile to be able to use the Jenkins shared library found: https://github.com/pace-neutrons/PACE-jenkins-shared-library thus allowing a cleaner and easier to maintain Jenkinsfile and consistency between the Jenkinsfiles of Herbert and Horace.

Use Jenkins shared library

---

_test/disabled_tests.md
_test/test_mpi/job_dispatcher_common_tests.m
herbert_core/admin/tmp_dir.m

trivial change should fix the issue with backslash

Backslash in tmp_dir on Jenkins

---

herbert_core/utilities/classes/@object_lookup/func_eval.m
herbert_core/utilities/classes/@object_lookup/func_eval_ind.m
herbert_core/utilities/classes/@object_lookup/object_array.m
herbert_core/utilities/classes/@object_lookup/object_elements.m
herbert_core/utilities/classes/@object_lookup/object_lookup.m
herbert_core/utilities/classes/@pdf_table/IX_dataset_1d.m
herbert_core/utilities/classes/@pdf_table/mean.m
herbert_core/utilities/classes/@pdf_table/pdf_table.m
herbert_core/utilities/classes/@pdf_table/rand.m
herbert_core/utilities/classes/@pdf_table/retain.m
herbert_core/utilities/classes/@pdf_table/var.m
herbert_core/utilities/classes/@pdf_table/width.m
herbert_core/utilities/classes/@pdf_table_array/pdf_table_array.m
herbert_core/utilities/classes/@pdf_table_array/rand_ind.m
herbert_core/utilities/classes/@pdf_table_lookup/pdf_table_lookup.m
herbert_core/utilities/classes/@pdf_table_lookup/rand_ind.m

Help edited to clarify the use of the various lookup options. In a few cases lines of code added to parse input argumnets more robustly. No changes to functionality.

Documentation and minor code improvements to parsing and checking

---

herbert_core/applications/multifit/@mfclass/private/mask_data_for_fit.m
herbert_core/applications/multifit/@mfclass/simulate.m

Fix `simulate`'s error handling (seems to be untested in Herbert?)

Fix outputs in simulate

---

_test/test_utilities/test_ortho.m
herbert_core/utilities/ortho_vec.m

This is small routine to produce two 3D vectors, orthogonal to the given one. Can be extended for more dimensions but not for the ticket

Small routine to produce orthogonal vector and unit test for it

---

CMakeLists.txt
_test/shared/matlab_xunit_ISISextras/@TestPerformance/TestPerformance.m
_test/shared/matlab_xunit_ISISextras/@TestPerformance/private/extract_data_.m
_test/shared/matlab_xunit_ISISextras/@TestPerformance/private/extract_x_axis_.m
_test/shared/matlab_xunit_ISISextras/@TestPerformance/private/parse_field_info_.m
_test/test_xunit_framework/TestPerformanceTester_PerfRez.xml
_test/test_xunit_framework/pTestPerformanceTester.m
_test/test_xunit_framework/test_TestPerformance.m
_test/test_xunit_framework/test_assertExceptionThrown.m
herbert_core/classes/MPIFramework/@parallel_config/parallel_config.m
herbert_core/utilities/general/is_file.m

This is bunch of small modifications to performance utilities, necessary for the analysis of the Performance [Horace, #706](https://github.com/pace-neutrons/horace/issues/706)

perfrofmance utilities

---

admin/herbert_mex_mpi.m
cmake/herbert_FindMPI.cmake

Minor changes, necessary for compilations on Ubuntu

fixing compilation on Ubuntu

---

herbert_core/utilities/maths/equal_to_tol.m

trivial fix, as described in ticket

structure comparison using all(ismember()) operation

---

herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst_DGdisk/IX_inst_DGdisk.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst_DGfermi/IX_inst_DGfermi.m
herbert_core/utilities/maths/private/sortStruct_private.m
herbert_core/utilities/maths/sortStruct.m

small changes making DGfermi and DGdisk classes not empty if created with empty constructor

Make DGfermi and DGdisk not empty by default

---

tools/build_config/Jenkinsfile

Allow Jenkins to safely use icdpacewin.

Pace win update

---

_test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m
herbert_core/applications/multifit/@mfclass/private/mask_data_for_fit.m

Starting to build structure to improve testing. Subsequent Horace PR once filesize workarounds worked out. 
Addresses #217

Restructure tobyfit tests

---

_test/test_instrument_classes/test_IX_sample.m
_test/test_instrument_classes/test_serialize_deserialize_instruments.m
herbert_core/classes/instrument_classes/instrument/@IX_null_sample/IX_null_sample.m
herbert_core/classes/instrument_classes/instrument/@IX_samp/IX_samp.m
herbert_core/classes/instrument_classes/instrument/@IX_sample/IX_sample.m
herbert_core/classes/instrument_classes/instrument/@IX_sample/private/convert_old_struct_.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst/IX_inst.m
herbert_core/utilities/classes/@serializable/serializable.m
herbert_core/utilities/misc/serialise.m

one bug #417 when array of instruments gets serialized

oriented lattice

---

_test/test_serializers/serializableTester1.m
_test/test_serializers/serializableTester2.m
herbert_core/classes/data_loaders/@a_detpar_loader_interface/a_detpar_loader_interface.m
herbert_core/classes/data_loaders/@a_loader/a_loader.m
herbert_core/classes/data_loaders/@rundata/rundata.m
herbert_core/classes/instrument_classes/@oriented_lattice/oriented_lattice.m
herbert_core/classes/instrument_classes/@oriented_lattice/private/build_oriented_lattice_.m
herbert_core/classes/instrument_classes/instrument/@IX_aperture/IX_aperture.m
herbert_core/classes/instrument_classes/instrument/@IX_experiment/IX_experiment.m
herbert_core/classes/instrument_classes/instrument/@IX_samp/IX_samp.m
herbert_core/classes/instrument_classes/instrument/@IX_sample/IX_sample.m
herbert_core/classes/instrument_classes/instrument/@IX_source/IX_source.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst/IX_inst.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst_DGdisk/IX_inst_DGdisk.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst_DGfermi/IX_inst_DGfermi.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_null_inst/IX_null_inst.m
herbert_core/utilities/classes/@serializable/private/from_bare_struct_.m
herbert_core/utilities/classes/@serializable/private/set_positional_and_key_val_arguments_.m
herbert_core/utilities/classes/@serializable/private/to_bare_struct_.m
herbert_core/utilities/classes/@serializable/serializable.m

renamed all indepFields methods into saveableFields methods

---

_test/test_data_loaders/test_gen_runfiles.m
_test/test_data_loaders/test_rundata_get.m
herbert_core/classes/data_loaders/@rundata/private/extract_id_from_filename_.m
herbert_core/classes/data_loaders/@rundata/rundata.m
herbert_core/classes/instrument_classes/@oriented_lattice/bmatrix.m
herbert_core/classes/instrument_classes/@oriented_lattice/calc_proj_matrix.m
herbert_core/classes/instrument_classes/@oriented_lattice/oriented_lattice.m
herbert_core/classes/instrument_classes/@oriented_lattice/private/recalculate_angular_units_values_.m
herbert_core/utilities/scientific/bmatrix.m

modification, necessary to bring to rundata to fix Horace test

fixed Horace init test

---

herbert_core/classes/MPIFramework/@ClusterMPI/ClusterMPI.m
herbert_core/classes/MPIFramework/@ClusterParpoolWrapper/ClusterParpoolWrapper.m
herbert_core/classes/MPIFramework/@ClusterWrapper/ClusterWrapper.m
herbert_core/classes/MPIFramework/@parallel_config/parallel_config.m
herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_cluster_.m
herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_worker_.m

From merged PR to `rel_3_6`
-----
* Add compiled worker changes
* Address PR comments and fix test fail
* Compiled workers: fixed windows mpiexec test fail

Compiled workers - Herbert changes (#434)

---

_test/shared/matlab_xunit/xunit/TestSuite.m
_test/test_IX_classes/test_IX_experiment.m
_test/test_data_loaders/test_rundata_get.m
herbert_core/classes/data_loaders/@rundata/rm_masked.m
herbert_core/classes/instrument_classes/instrument/@IX_experiment/IX_experiment.m
herbert_core/classes/instrument_classes/instrument/@IX_samp/IX_samp.m
herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst/IX_inst.m

This is small change dedicated to storing run_id-s in IX_experiment

runid in IX_experiment

---

admin/dump_profile.m
admin/worker_v2.m.template
herbert_core/classes/MPIFramework/parallel_worker.m
herbert_core/utilities/misc/str2logical.m

Add quick parallel profiling option through the `DO_PARALLEL_MATLAB_PROFILING` environment variable on a per process level.

Add parallel profiling capability

---

herbert_core/utilities/maths/equal_to_tol.m

Fix printing in `equal_to_tol`

Fix equal_to_tol printing
